server:
  port: ${port:8001}
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1    # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可
spring:
#  application:
#    name: recruit-saas-gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由,可以根据服务名从注册中心获取到服务实例

  profiles:
    active: dev
  main:
    web-application-type: reactive  #设置WebApplication类型为reactive

logging:
  level:
    root: info
