server:
  port: ${port:8001}
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1    # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可
spring:
  application:
    name: recruit-saas-gateway-service

  profiles:
    active: dev
  main:
    web-application-type: reactive  #设置WebApplication类型为reactive

logging:
  level:
    root: info
