spring:
  cloud:
    #Nacos服务注册与发现配置
    nacos:
      discovery:
        server-addr: remote-centos:8848/   #设置Nacos注册中心地址
        namespace: 166004f2-bd1e-4d70-aa0d-0b929a1e28b2   #设置Nacos服务namespace
  datasource:
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://remote-centos:3306/recruit_saas?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 12345678
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1

#MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml  #指定Mapper XML地址
  global-config:
    db-config:
      id-type: assign_id  #指定MyBatis Plus 主键生成策略